runtime: go119
main: ./cmd
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_treshold: 2
  success_treshold: 2
readiness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_treshold: 2
  success_treshold: 2
  app_start_timeout_sec: 300
